import Head from "next/head";

import { Inter } from "@next/font/google";

import { Flex, HStack } from "@chakra-ui/react";
import Profile from "../Components/Profile";
import Skills from "../Components/Skills";
import Timeline from "../Components/Timeline";
import Projects from "../Components/Projects";
import Navbar from "../Components/Navbar";

const inter = Inter({ subsets: ["latin"] });

function Home({ profile, projects }) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Flex>
        <HStack>
          <Flex gap="6" w={"500px"} direction="column">
            <Profile profile={profile} />
            <Skills />
            <Timeline />
          </Flex>
          <Flex direction="column" width="1000px">
            <Projects data={projects} />
          </Flex>
        </HStack>
      </Flex>
    </>
  );
}
export async function getServerSideProps() {
  let res = await fetch(`https://api.github.com/users/shivshankar`);
  let data = await res.json();
  let res1 = await fetch(
    `https://api.github.com/search/repositories?q=user:shivshankar0965+fork:true&sort=updated&per_page=10&type=Repositories`
  );
  let data1 = await res1.json();
  return {
    props: {
      profile: data,
      projects: data1,
    },
  };
}
export default Home;
